services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: dev
      POSTGRES_DB: marketing
    ports: ['5432:5432']
    volumes: ['./data/postgres:/var/lib/postgresql/data']
  redis:
    image: redis:7
    ports: ['6379:6379']
  backend:
    build: ./backend
    command: node server.js
    ports: ['4000:4000']
    environment:
      - NODE_ENV=development
      - PORT=4000
      - POSTGRES_URL=postgres://dev:dev@postgres:5432/marketing
      - REDIS_URL=redis://redis:6379
    depends_on: ['postgres','redis']
  frontend:
    build: ./frontend
    command: npm run dev
    ports: ['3000:3000']
    environment:
      - NODE_ENV=development
    depends_on: ['backend']
